#cloud-config
autoinstall:
  version: 1
  
  # ====================================================================
  # CONFIGURAÇÃO DE ARMAZENAMENTO
  # ====================================================================
  storage:
    wipe: all
    layout:
      name: lvm
      match:  
        path: /dev/nvme0n1
      password: "$6$62BXzCtLeYnZrhUs$1n39Rl1ZHCW7G9M7CKe2d93DVG/HOffMXjoZuo7e190jVr0IoVlchVNdGL2wX2ueQHKNSno5tJJ5i9rMTqDDs1"

  # ====================================================================
  # CONFIGURAÇÕES DE SISTEMA (Identidade e Localização)
  # ====================================================================
  identity:
    hostname: daniel_sammartano
    username: testefinal
    password: "$6$62BXzCtLeYnZrhUs$1n39Rl1ZHCW7G9M7CKe2d93DVG/HOffMXjoZuo7e190jVr0IoVlchVNdGL2wX2ueQHKNSno5tJJ5i9rMTqDDs1" 
    
  locale: pt_BR
  timezone: America/Sao_Paulo
  
  keyboard:
    layout: br

  # ====================================================================
  # INSTALAÇÃO DECLARATIVA DE APLICATIVOS (APT e SNAP)
  # ====================================================================
  packages:
    # Incluindo libglib2.0-bin para garantir que o comando 'gsettings' exista
    - docker.io
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - gimp
    - git
    - wget
    - libglib2.0-bin 

  snaps:
    # Aplicações instaladas via Snap Store
    - name: spotify
      channel: stable
      classic: false
    - name: postman
      channel: stable
      classic: false
    - name: slack
      channel: stable
      classic: false
    - name: code # VS Code
      channel: stable
      classic: true
    - name: dbeaver-ce
      channel: stable
      classic: false
      
  # Configurações adicionais
  codecs:
    install: true
  drivers:
    install: true
  updates: all
  shutdown: reboot

  # ====================================================================
  # COMANDOS DE PÓS-INSTALAÇÃO (Configurações de Usuário, Extensões e Wallpaper)
  # ====================================================================
  late-commands:
    # Variável de usuário para simplificar
    - |
      TARGET_USER="testefinal"
      IMAGE_URL="https://i.ibb.co/cwtDVCS/Frame-6.png"
      IMAGE_PATH="/home/${TARGET_USER}/Frame-6.png"
      
    # 1. Update/Upgrade inicial
    - curtin in-target -- apt update
    - curtin in-target -- apt upgrade -y
      
    # 2. DOWNLOAD E PERMISSÃO DO PAPEL DE PAREDE
    - |
      # Baixa a imagem diretamente para o diretório do usuário
      curtin in-target -- sh -c "wget -O \"${IMAGE_PATH}\" \"${IMAGE_URL}\""
      # Garante que o usuário é o proprietário do arquivo
      curtin in-target -- chown "${TARGET_USER}":"${TARGET_USER}" "${IMAGE_PATH}"
      
    # 3. DEFINIÇÃO DO PAPEL DE PAREDE USANDO GSETTINGS (GNOME)
    # Roda o comando gsettings no contexto do usuário 'testefinal'.
    - |
      # Configura o wallpaper para o modo claro (padrão)
      curtin in-target -- su - "${TARGET_USER}" -c "gsettings set org.gnome.desktop.background picture-uri file://${IMAGE_PATH}"
      # Configura o wallpaper para o modo escuro
      curtin in-target -- su - "${TARGET_USER}" -c "gsettings set org.gnome.desktop.background picture-uri-dark file://${IMAGE_PATH}"

  power-state:
    delay: 5
    mode: reboot
