#cloud-config
autoinstall:
  version: 1
  
  # --- Configuração de Armazenamento com LVM e Criptografia ---
  storage:
    wipe: all
    layout:
      name: lvm
      match:
        path: /dev/nvme0n1
      password: "#FormatAvita@@!" 
      
  # --- Identidade do Sistema e Usuário ---
  identity:
    hostname: AVTec-victorpersike
    username: victorpersike
    password: "$6$vEfMZxxLdKOo3CBb$atGwGiCpF.ZlVPS6A3vawQYlYAYgZaEhdhAYMGpw5OeZm3t2rxLqcpQCouS9jro2fwb9uQ3Wm21QTVR1JIAEU0"
  
  # --- Localização e Idioma ---
  locale: pt_BR
  timezone: America/Sao_Paulo
  
  # Configuração inicial do teclado
  keyboard:
    layout: br
    
  # --- Pacotes DEB (APT) - curl/wget/git já estão aqui ---
  packages:
    - docker.io
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - gimp
    - git
    - wget
  
  # --- Pacotes Snap ---
  snaps:
    - name: spotify
      channel: stable
      classic: false
    - name: postman
      channel: stable
      classic: false
    - name: slack
      channel: stable
      classic: false
    - name: code
      channel: stable
      classic: true
    - name: dbeaver-ce
      channel: stable
      classic: false
    - name: dotnet-sdk
      channel: 8.0/stable
      classic: true

  # --- Drivers e Codecs ---
  codecs:
    install: true
  drivers:
    install: true
  updates: all

  # --- Comandos Pós-Instalação (Executados no Primeiro Boot) ---
  user-data:
    runcmd:
      # 1. **(Teclado ThinkPad - Corrigindo o layout gráfico)**
      - setxkbmap -model thinkpad -layout br
      - su - victorpersike -c "echo 'setxkbmap -model thinkpad -layout br' >> /home/victorpersike/.xsessionrc"
      
      # 2. **Atualização Completa do Sistema (Correção de Erro Anterior)**
      - apt update
      - apt upgrade -y

      - apt install notion
      
  # --- Estado Final ---
  power-state:
    delay: 5
    mode: reboot
