#cloud-config
autoinstall:
  version: 1
  identity:
    realname: 'Dionatan Simioni'
    hostname: ubuntu-test-crypt
    username: diolinux
    # Hash SHA512 para o usuário 'diolinux'
    password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3' 
  locale: pt_BR.utf8
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo"

  # --- CONFIGURAÇÃO DE ARMAZENAMENTO AUTOMÁTICA E ROBUSTA ---
  # Esta é a forma mais confiável de configurar a criptografia total.
  storage:
    layout:
      name: encrypted # Usa o layout automático de criptografia total (LUKS sobre LVM)
      device: /dev/nvme0n1 # Dispositivo a ser usado
      key: Avita123 # Senha de criptografia em texto plano (CUIDADO!)
      # IMPORTANTE: Se o seu sistema for UEFI, ele criará as partições /boot e /boot/efi
      # automaticamente. Não é necessário definir particionamento manual.
      
  # --- Configurações de Pós-Instalação ---
  updates: all
  shutdown: reboot
