#cloud-config
autoinstall:
  version: 1
  
  # ====================================================================
  # CONFIGURAÇÃO DE ARMAZENAMENTO
  # ====================================================================
  storage:
    wipe: all
    layout:
      name: lvm
      match:  
        path: /dev/nvme0n1
      password: "$6$62BXzCtLeYnZrhUs$1n39Rl1ZHCW7G9M7CKe2d93DVG/HOffMXjoZuo7e190jVr0IoVlchVNdGL2wX2ueQHKNSno5tJJ5i9rMTqDDs1"

  # ====================================================================
  # CONFIGURAÇÕES DE SISTEMA (Identidade e Localização)
  # ====================================================================
  identity:
    hostname: daniel_sammartano
    username: testefinal
    password: "$6$62BXzCtLeYnZrhUs$1n39Rl1ZHCW7G9M7CKe2d93DVG/HOffMXjoZuo7e190jVr0IoVlchVNdGL2wX2ueQHKNSno5tJJ5i9rMTqDDs1" 
    
  locale: pt_BR
  timezone: America/Sao_Paulo
  
  keyboard:
    layout: br

  # ====================================================================
  # INSTALAÇÃO DECLARATIVA DE APLICATIVOS (APT e SNAP)
  # ====================================================================
  packages:
    # Pacotes APT essenciais (Docker, Git, utilitários, libglib2.0-bin para gsettings)
    - docker.io
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - gimp
    - git
    - wget
    - libglib2.0-bin # Necessário para o comando 'gsettings'

  snaps:
    # Aplicações instaladas via Snap Store
    - name: spotify
      channel: stable
      classic: false
    - name: postman
      channel: stable
      classic: false
    - name: slack
      channel: stable
      classic: false
    - name: code # VS Code
      channel: stable
      classic: true
    - name: dbeaver-ce
      channel: stable
      classic: false
      
  # Configurações adicionais
  codecs:
    install: true
  drivers:
    install: true
  updates: all
  shutdown: reboot

  # ====================================================================
  # COMANDOS DE PÓS-INSTALAÇÃO (Configurações de Usuário, Extensões e Wallpaper)
  # Este bloco foi corrigido para resolver o erro de execução.
  # ====================================================================
   late-commands:
    # 1. Update/Upgrade inicial (Mantido)
    - curtin in-target -- apt update
    - curtin in-target -- apt upgrade -y
      
    # 2. DOWNLOAD DA IMAGEM E GARANTIA DE PERMISSÃO (SIMPLIFICADO)
    # Baixa a imagem diretamente para /home/testefinal/Frame-6.png e garante que o proprietário seja o usuário.
    # O comando é executado no shell do root, mas atua no diretório do usuário.
    - curtin in-target -- sh -c "wget -O /home/testefinal/Frame-6.png https://i.ibb.co/cwtDVCS/Frame-6.png && chown testefinal:testefinal /home/testefinal/Frame-6.png"
      
    # 3. DEFINIÇÃO DO PAPEL DE PAREDE (SIMPLIFICADO E ROBUSTO)
    # Roda os comandos gsettings diretamente no contexto do usuário testefinal.
    - curtin in-target -- su - testefinal -c "gsettings set org.gnome.desktop.background picture-uri file:///home/testefinal/Frame-6.png"
    - curtin in-target -- su - testefinal -c "gsettings set org.gnome.desktop.background picture-uri-dark file:///home/testefinal/Frame-6.png"

  power-state:
    delay: 5
    mode: reboot
