#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Daniel Avita'
        hostname: ubuntu-desktop
        username: danielavita
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"
    
    # -------------------------------------------------------------
    # CONFIGURAÇÃO DE STORAGE FINAL E MAIS ESTÁVEL (NVME0N1 LVM/LUKS)
    # -------------------------------------------------------------
    storage:
        config:
            # 1. Limpa o disco principal
            - type: disk
              name: nvme0n1 # Confirmado para NVMe
              ptable: gpt
              wipe: superblock-recursive
              
            # 2. Partição LUKS que cobre o restante do disco após as partições EFI/BOOT.
            - type: partition
              disk: nvme0n1
              size: 0 # O restante do disco
              
            # 3. Camada de Criptografia LUKS
            - type: crypt
              volume: nvme0n1
              # Senha de criptografia LVM/LUKS (Hash fornecido)
              password: '$6$dEsPnw6B0uPMsJtg$R8DQ9KoMZIR5/RW690CIyXcx/qQWQPBu1Ov0u9ctiWvibXbQB4vgPDbMDpPw3mNx08HNhL9Or3F9RL/rxiQJK0'
              # Nome do mapeamento
              name: nvme-crypt
              
            # 4. Volume Group (VG) LVM dentro do contêiner LUKS
            - type: lvm_volgroup
              name: vg-system
              volumes:
                - nvme-crypt
                
            # 5. Logical Volume para a Raiz (automatic: true cria / e swap)
            - type: lvm_partition
              volgroup: vg-system
              size: 0 # O restante do VG
              name: lv-root
              
            # 6. Formatação e Montagem
            - type: format
              volume: lv-root
              fstype: ext4
            - type: mount
              volume: lv-root
              path: /
              
            # 7. Habilita o particionamento automático para EFI e /boot (Recomendado)
            - type: mount
              path: /boot/efi
              device: nvme0n1
              partition: 1 # O instalador deve criar as partições automaticamente aqui
              
            - type: mount
              path: /boot
              device: nvme0n1
              partition: 2
              
            # 8. Criação automática de Swap (dentro do LVM)
            - type: lvm_partition
              volgroup: vg-system
              size: 4096M # 4GB de Swap, ajuste conforme necessário
              name: lv-swap
            - type: format
              volume: lv-swap
              fstype: swap
            - type: mount
              volume: lv-swap
              path: none
              
    # --- Softwares e Comandos (Mantidos) ---
    packages:
        - libreoffice
        - gimp
        - git
        - wget
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
    
    snaps:
        - name: spotify
          channel: stable
          classic: false
        - name: slack
          channel: stable
          classic: false
    
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
    
    late-commands:
        # --- Instalação de Programas (Bloco mantido o mais estável possível) ---
        - |
          echo "--- 1. INICIANDO INSTALAÇÕES DE SISTEMA (ROOT) ---"
          
          # DBeaver, Docker, VS Code, Repositórios, etc.
          echo "Configurando repositórios e chaves..."
          echo "deb [signed-by=/usr/share/keyrings/dbeaver.gpg] https://dbeaver.io/debs/dbeaver-ce /" | tee /etc/apt/sources.list.d/dbeaver.list
          wget -qO - https://dbeaver.io/debs/dbeaver.gpg.key | gpg --dearmor | tee /usr/share/keyrings/dbeaver.gpg > /dev/null
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor | tee /usr/share/keyrings/docker.gpg > /dev/null
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /usr/share/keyrings/microsoft.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" | tee /etc/apt/sources.list.d/vscode.list
          wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          
          # Update e Instalação (Agrupada)
          echo "Executando apt update e instalações de pacotes externos..."
          apt-get update
          apt-get install -y dbeaver-ce docker-ce powershell code

          # Postman (Instalação Global)
          echo "Instalando Postman Globalmente..."
          wget https://dl.pstmn.io/download/latest/linux64 -O /tmp/postman.tar.gz
          tar -xzf /tmp/postman.tar.gz -C /opt
          ln -sf /opt/Postman/Postman /usr/bin/postman
          rm /tmp/postman.tar.gz
          cat << EOF > /usr/share/applications/postman.desktop
          [Desktop Entry]
          Type=Application
          Name=Postman
          Icon=/opt/Postman/app/resources/app/assets/icon.png
          Exec="/opt/Postman/Postman"
          Comment=Postman Desktop App
          Categories=Development;Code;
          EOF
          
          # Configurações de Permissão (Root)
          echo "Configurando grupos de permissão e serviços..."
          groupadd docker || true 
          usermod -aG docker danielavita
          systemctl enable docker
          
          # 2. INSTALAÇÃO DE PROGRAMAS DE USUÁRIO (NVM e .NET Core)
          echo "--- 2. INICIANDO INSTALAÇÕES DE USUÁRIO (DANIELAVITA) ---"
          su - danielavita -c '
            echo "Iniciando instalação do NVM..."
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
            
            echo "Iniciando instalação do .NET Core..."
            wget https://dot.net/v1/dotnet-install.sh -O /tmp/dotnet-install.sh
            chmod +x /tmp/dotnet-install.sh
            /tmp/dotnet-install.sh --channel 6.0
            
            echo "Configurando NuGet..."
            /home/danielavita/.dotnet/dotnet nuget add source https://gitlab.com/api/v4/projects/26749643/packages/nuget/index.json --name Gitlab --username gitlab+deploy-token-982472 --password h4V8PmDAVBzuHNAvsjAz --store-password-in-clear-text
          '
          
          # Link Simbólico Global para .NET (Root)
          echo "Criando link simbólico para dotnet..."
          ln -s /home/danielavita/.dotnet/dotnet /usr/bin/dotnet

          echo "--- INSTALAÇÃO AUTOMÁTICA CONCLUÍDA! ---"
