#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Dionatan Simioni'
        hostname: ubuntu-desktop
        username: diolinux
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"    
    
    packages:
        # Docker e dependências
        - docker.io
        - apt-transport-https 
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        # Outros pacotes
        - libreoffice
        - gimp
        - git
        - wget
    snaps:
        - name: spotify
          channel: stable
          classic: false
        - name: postman 
          channel: stable
          classic: false
        - name: slack
          channel: stable
          classic: false
        - name: code # VS Code
          channel: stable
          classic: true 
        - name: dbeaver-ce 
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
    
    # --- Comandos Pós-Instalação ---
    late-commands:
        # 1. Instalação do NVM (como usuário diolinux)
        - |
          su - diolinux -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash"

        # 2. Instalação do .NET Core 6.0 e Configuração do NuGet (como usuário diolinux)
        # Atenção: O script foi ajustado para evitar o uso de 'sudo' desnecessário
        # e para garantir que o link simbólico aponte para o diretório correto do usuário.
        - |
          su - diolinux -c '
            wget https://dot.net/v1/dotnet-install.sh -O /tmp/dotnet-install.sh && 
            chmod +x /tmp/dotnet-install.sh && 
            /tmp/dotnet-install.sh --channel 6.0 && 
            
            # O link simbólico precisa ser criado como root (para /usr/bin) mas deve apontar para o home do usuário.
            # Este é o único comando que deve ser executado com privilégios de root, mas o alvo é o caminho do usuário.
            sudo ln -s /home/diolinux/.dotnet/dotnet /usr/bin/dotnet && 
            
            # Configuração do NuGet (como usuário diolinux)
            /home/diolinux/.dotnet/dotnet nuget add source https://gitlab.com/api/v4/projects/26749643/packages/nuget/index.json --name Gitlab --username gitlab+deploy-token-982472 --password h4V8PmDAVBzuHNAvsjAz --store-password-in-clear-text
          '
