#cloud-config
autoinstall:
  version: 1
  
  # ====================================================================
  # CONFIGURAÇÃO DE ARMAZENAMENTO MAIS SIMPLES
  # Usa o layout 'lvm' padrão do instalador no disco especificado,
  # ativando a criptografia com uma senha.
  # ====================================================================
  storage:
    layout:
      name: lvm
      match: 
        # Garante que a instalação ocorra APENAS no disco /dev/nvme0n1
        path: /dev/nvme0n1
      
      # ⚠️ MUDE A SENHA! Use uma senha forte para o seu teste.
      password: Senhafoda123@

  # Configurações obrigatórias para um autoinstall completo:
  
  # Define o usuário padrão para login após a instalação
  identity:
    hostname: notebook-ubuntu
    username: testuser
    password: $6$EAyehhfqepzaGX78$k4Qceki0nxJKS2.ZxcWyWjn7db3p7/0Qu.S6pr32pIqVpzfFmwnOj/.XKgY6x3ADG077lE.DoNwMpXZ2aXr3q. # Substitua pelo hash de uma senha forte (ou use plaintext_password)
    # plaintext_password: senha_login_simples

  # Define o pacote a ser instalado (server é o padrão)
  package:
    name: ubuntu-server
  
  # Configurações regionais
  locale: pt_BR
  keyboard:
    layout: br
    variant: abnt2
  timezone: America/Sao_Paulo
  
  # Comandos que serão executados após a instalação (exemplo)
  late-commands:
    - curtin in-target -- apt update
    - curtin in-target -- apt upgrade -y
    
  # Ação final
  power-state:
    delay: 5
    mode: reboot
