#cloud-config
autoinstall:
  version: 1

  # ====================================================================
  # CONFIGURAÇÃO DE ARMAZENAMENTO
  # ====================================================================
  storage:
    wipe: all
    layout:
      name: lvm
      match:  
        path: /dev/nvme0n1
      
      # SENHA DE CRIPTOGRAFIA (LUKS)
      password: 'Avita123"'

  # ====================================================================
  # CONFIGURAÇÕES DE SISTEMA (Identidade e Localização)
  # ====================================================================
  identity:
    hostname: daniel_sammartano
    username: testefinal
    password: 'Avita123"'
    
  locale: pt_BR
  timezone: America/Sao_Paulo
  
  keyboard:
    layout: br

  # ====================================================================
  # INSTALAÇÃO DECLARATIVA DE APLICATIVOS (APT e SNAP)
  # Removido 'docker-compose-plugin' para evitar a falha de instalação.
  # ====================================================================
  packages:
    - docker.io
    - git
    - gimp
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - wget
    - libglib2.0-bin 

  snaps:
    - name: spotify
      channel: stable
    - name: postman
      channel: stable
    - name: slack
      channel: stable
    - name: code
      channel: stable
      classic: true
    - name: dbeaver-ce
      channel: stable
      
  # Configurações adicionais
  codecs:
    install: true
  drivers:
    install: true
  updates: all

  # ====================================================================
  # COMANDOS DE PÓS-INSTALAÇÃO (ROOT)
  # ====================================================================
  late-commands:
    # Atualiza repositórios
    - curtin in-target -- apt update
    # Atualiza pacotes instalados
    - curtin in-target -- apt upgrade -y
    # Adiciona o usuário ao grupo docker
    - curtin in-target -- usermod -aG docker testefinal
      
  # ====================================================================
  # AÇÃO FINAL (Colocado na sub-chave correta para evitar o aviso/erro)
  # ====================================================================
  power-state:
    delay: 5
    mode: reboot
