#cloud-config
autoinstall:
  version: 1

  # CONFIGURAÇÃO DE ARMAZENAMENTO (Criptografia e LVM)
  storage:
    wipe: all
    layout:
      name: lvm
      match:
        path: /dev/nvme0n1
      password: 'Senha2024'
  
  # CONFIGURAÇÕES DE SISTEMA BÁSICAS
  identity:
    # hostname: Nome visível na rede, sem caracteres especiais é mais seguro
    hostname: daniel-pc
    # username: O nome de usuário a ser criado.
    username: daniel.sammartano
    password: 'Senha2024'
    
  locale: pt_BR
  timezone: America/Sao_Paulo
  keyboard:
    layout: br

  # INSTALAÇÃO DE APLICATIVOS (APT e SNAP)
  packages:
    - docker.io
    - git
    - gimp
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - wget
    - libglib2.0-bin
    - hunspell-pt-br
    - wportuguese
    - wpasupplicant
    
  snaps:
    - name: spotify
      channel: stable
    - name: postman
      channel: stable
    - name: slack
      channel: stable
    - name: code
      channel: stable
      classic: true
    - name: dbeaver-ce
      channel: stable
      
  # Configurações adicionais
  codecs:
    install: true
  drivers:
    install: true
  updates: all

  # COMANDOS DE PÓS-INSTALAÇÃO (MÍNIMOS)
  late-commands:
    # AÇÃO FINAL: Reinicia o sistema
    - curtin in-target -- /sbin/reboot 5
