#cloud-config
autoinstall:
  version: 1

  # ====================================================================
  # CONFIGURAÇÃO DE ARMAZENAMENTO
  # ====================================================================
  storage:
    wipe: all
    layout:
      name: lvm
      match:  
        path: /dev/nvme0n1
      
      # SENHA DE CRIPTOGRAFIA (LUKS)
      password: 'Avita123"'

  # ====================================================================
  # CONFIGURAÇÕES DE SISTEMA (Identidade e Localização)
  # ====================================================================
  identity:
    hostname: daniel_sammartano
    username: testefinal
    password: 'Avita123"'
    
  locale: pt_BR
  timezone: America/Sao_Paulo
  
  keyboard:
    layout: br

  # ====================================================================
  # INSTALAÇÃO DECLARATIVA DE APLICATIVOS (APT e SNAP)
  # ====================================================================
  packages:
    - docker.io
    - git
    - gimp
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - wget
    - libglib2.0-bin
    - docker-compose-plugin

  snaps:
    - name: spotify
      channel: stable
    - name: postman
      channel: stable
    - name: slack
      channel: stable
    - name: code
      channel: stable
      classic: true
    - name: dbeaver-ce
      channel: stable
      
  # Configurações adicionais
  codecs:
    install: true
  drivers:
    install: true
  updates: all

  # ====================================================================
  # COMANDOS DE PÓS-INSTALAÇÃO (ROOT)
  # ====================================================================
  late-commands:
    - curtin in-target -- apt update
    - curtin in-target -- apt upgrade -y
    - curtin in-target -- usermod -aG docker testefinal
      
  # ====================================================================
  # CONFIGURAÇÃO DE USUÁRIO (PRIMEIRO BOOT)
  # ====================================================================
  user-data:
    runcmd:
      # Comando executado como testefinal em uma ÚNICA LINHA para evitar erros de indentação.
      - su - testefinal -c 'export HOME=/home/testefinal; wget https://i.ibb.co/cwtDVCS/Frame-6.png -O $HOME/Downloads/Frame-6.png; gsettings set org.gnome.desktop.background picture-uri "file://$HOME/Downloads/Frame-6.png"; gsettings set org.gnome.desktop.background picture-uri-dark "file://$HOME/Downloads/Frame-6.png"'
      
  # ====================================================================
  # AÇÃO FINAL
  # ====================================================================
  power-state:
    delay: 5
    mode: reboot
