#cloud-config
autoinstall:
  version: 1
  identity:
    realname: 'Dionatan Simioni'
    hostname: ubuntu-desktop
    username: diolinux
    # Hash SHA512 para o usuário 'diolinux'
    password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3' 
  locale: pt_BR.utf8
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo"

  # --- Configuração de Armazenamento com Criptografia LUKS/LVM (CORRIGIDO) ---
  storage:
    config:
    # 1. Identificação e Limpeza do Disco Principal
    - id: disk-nvme
      type: disk
      match:
        path: /dev/nvme0n1
      ptable: gpt
      wipe: superblock-recursive
      
    # 2. Partição /boot (Partição EFI em sistemas UEFI, 512 MB)
    - id: partition-boot
      type: partition
      device: disk-nvme
      size: 536870912 
      flag: boot
      grub_device: true 

    # 3. Partição Principal (o restante do disco, a ser criptografada)
    - id: partition-luks
      type: partition
      device: disk-nvme
      size: 0 

    # 4. Criptografia LUKS sobre a partição principal
    - id: encryption-luks
      type: encrypt
      volume: partition-luks
      password: Avita123 

    # 5. Volume Group LVM sobre o volume criptografado (CORRIGIDO: usando 'devices')
    - id: volgroup-system
      type: lvm_volgroup
      name: vg-system
      devices:  # <--- CORREÇÃO: Deve ser 'devices' e não 'volumes'
      - encryption-luks 

    # 6. Logical Volume (raiz)
    - id: logicalvolume-root
      type: lvm_partition
      volgroup: volgroup-system
      size: 0 
      name: lv-root

    # 7. Formatação e Montagem
    - id: format-boot
      type: format
      volume: partition-boot
      fstype: ext4
    - id: format-root
      type: format
      volume: logicalvolume-root
      fstype: ext4
    - id: mount-boot
      type: mount
      volume: format-boot
      path: /boot
    - id: mount-root
      type: mount
      volume: format-root
      path: /
      
  # --- Configurações de Software e Pós-Instalação (INALTERADAS) ---
  packages:
    - libreoffice
    - gimp
    - git
    - wget
    - docker.io
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

  snaps:
    - name: spotify
      channel: stable
      classic: false
    - name: postman
      channel: stable
      classic: false
    - name: slack
      channel: stable
      classic: false
    - name: code
      channel: stable
      classic: true
    - name: dbeaver-ce
      channel: stable
      classic: false

  codecs:
    install: true
  drivers:
    install: true

  updates: all
  shutdown: reboot

  late-commands:
    - |
      curl -o /target/home/diolinux/install-nvm.sh https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh
      echo 'su - diolinux -c "bash /home/diolinux/install-nvm.sh"' >> /target/var/lib/cloud/scripts/per-instance/nvm.sh
      chmod +x /target/var/lib/cloud/scripts/per-instance/nvm.sh
