#cloud-config
autoinstall:
  version: 1

  # CONFIGURAÇÃO DE ARMAZENAMENTO (Criptografia e LVM)
  storage:
    wipe: all
    layout:
      name: lvm
      match:
        path: /dev/nvme0n1
      password: 'Senha2024'
  
  # CONFIGURAÇÕES DE SISTEMA
  identity:
    hostname: daniel_sammartano
    username: Daniel.Sammartano
    password: 'Senha2024'
    
  locale: pt_BR
  timezone: America/Sao_Paulo
  keyboard:
    layout: br

  # INSTALAÇÃO DE APLICATIVOS (APT e SNAP)
  packages:
    - docker.io
    - git
    - gimp
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - wget
    - libglib2.0-bin 
    - hunspell-pt-br # Adicionado para completar a localização PT-BR
    - wportuguese    # Adicionado para completar a localização PT-BR
    - wpasupplicant  # Adicionado para completar a instalação de drivers

  snaps:
    - name: spotify
      channel: stable
    - name: postman
      channel: stable
    - name: slack
      channel: stable
    - name: code
      channel: stable
      classic: true
    - name: dbeaver-ce
      channel: stable
      
  # Configurações adicionais
  codecs:
    install: true
  drivers:
    install: true
  updates: all

  # COMANDOS DE PÓS-INSTALAÇÃO (ROOT)
  late-commands:
    # 1. Atualiza repositórios
    - curtin in-target -- apt update
    # 2. Atualiza pacotes instalados
    - curtin in-target -- apt upgrade -y
    # 3. CORREÇÃO: Adiciona o usuário ao grupo docker usando a formatação provável:
    # (minúsculas e ponto substituído por underscore)
    - curtin in-target -- usermod -aG docker daniel_sammartano
    
    # 4. AÇÃO FINAL: Reinicia o sistema (Movido para dentro dos comandos)
    - curtin in-target -- /sbin/reboot 5
