#cloud-config
autoinstall:
  version: 1

  # --- ARMAZENAMENTO COM LVM E CRIPTOGRAFIA ---
  storage:
    wipe: all
    layout:
      name: lvm
      match:
        path: /dev/nvme0n1
      password: "#FormatAvita@@!"

  # --- IDENTIDADE DO SISTEMA ---
  identity:
    hostname: AVTec-rodrigomesquita
    username: rodrigomesquita
    password: "$6$zS3mqBECxkp6I5o7$QUva55pXxwOjHd3m8s2aJhz9NjpwLRXo24z.46LRPTmcKlovKqbYMFSCSRSMey2mpSO3h.mGjJIV2iltWccxS/"  #Avita123

  # --- LOCALIZAÇÃO ---
  locale: pt_BR
  timezone: America/Sao_Paulo

  keyboard:
    layout: br

  # --- PACOTES APT ---
  packages:
    - docker.io
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - gimp
    - git
    - wget
    - unzip
    - nano
    - software-properties-common

  # --- PACOTES SNAP ---
  snaps:
    - name: spotify
      channel: stable
      classic: false
    - name: postman
      channel: stable
      classic: false
    - name: slack
      channel: stable
      classic: false
    - name: code
      channel: stable
      classic: true
    - name: dbeaver-ce
      channel: stable
      classic: false
    - name: dotnet-sdk
      channel: 8.0/stable
      classic: true

  # --- DRIVERS E CODECS ---
  codecs:
    install: true
  drivers:
    install: true
  updates: all

  # --- CONFIGURAÇÕES PÓS-INSTALAÇÃO ---
  user-data:
    runcmd:
     - DEBIAN_FRONTEND=noninteractive apt update -y && DEBIAN_FRONTEND=noninteractive apt upgrade -y
     - setxkbmap -model thinkpad -layout br
     - su - rodrigomesquita -c "echo 'setxkbmap -model thinkpad -layout br' >> ~/.xsessionrc"
     - su - rodrigomesquita -c "curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash && source ~/.nvm/nvm.sh && nvm install 18 && nvm use 18"
     - bash -c "sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose && docker-compose --version"
     - su - rodrigomesquita -c "mkdir -p ~/Imagens && wget -O ~/Imagens/novo-wallpaper.png https://i.ibb.co/pjFjN4hS/Novos-colaboradores-2-2.png && gsettings set org.gnome.desktop.background picture-uri 'file:///home/rodrigomesquita/Imagens/novo-wallpaper.png' && gsettings set org.gnome.desktop.background picture-uri-dark 'file:///home/rodrigomesquita/Imagens/novo-wallpaper.png'"
  # --- ESTADO FINAL ---
  power-state:
    delay: 5
    mode: reboot
