#cloud-config
autoinstall:
  version: 1

  # --- ARMAZENAMENTO COM LVM E CRIPTOGRAFIA ---
  storage:
    wipe: all
    layout:
      name: lvm
      match:
        path: /dev/nvme0n1
      password: "#FormatAvita@@!"

  # --- IDENTIDADE DO SISTEMA ---
  identity:
    hostname: AVTec-victorpersike
    username: victorpersike
    password: "$6$vEfMZxxLdKOo3CBb$atGwGiCpF.ZlVPS6A3vawQYlYAYgZaEhdhAYMGpw5OeZm3t2rxLqcpQCouS9jro2fwb9uQ3Wm21QTVR1JIAEU0"

  # --- LOCALIZAÇÃO ---
  locale: pt_BR
  timezone: America/Sao_Paulo

  keyboard:
    layout: br

  # --- PACOTES APT ---
  packages:
    - docker.io
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - gimp
    - git
    - wget
    - unzip
    - nano
    - software-properties-common

  # --- PACOTES SNAP ---
  snaps:
    - name: spotify
      channel: stable
      classic: false
    - name: postman
      channel: stable
      classic: false
    - name: slack
      channel: stable
      classic: false
    - name: code
      channel: stable
      classic: true
    - name: dbeaver-ce
      channel: stable
      classic: false
    - name: dotnet-sdk
      channel: 8.0/stable
      classic: true

  # --- DRIVERS E CODECS ---
  codecs:
    install: true
  drivers:
    install: true
  updates: all

  # --- CONFIGURAÇÕES PÓS-INSTALAÇÃO ---
  user-data:
    runcmd:
      # --- Teclado ---
      - setxkbmap -model thinkpad -layout br
      - su - victorpersike -c "echo 'setxkbmap -model thinkpad -layout br' >> /home/victorpersike/.xsessionrc"

      # --- Atualização do sistema ---
      - apt-get update -y
      - apt-get upgrade -y
      - apt-get autoremove -y
      - apt-get autoclean -y

      # --- Corrige permissões e grupos do Docker ---
      - usermod -aG docker victorpersike
      - systemctl enable docker
      - systemctl start docker

      # --- Instala Docker Compose ---
      - curl -fsSL https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
      - docker-compose version || true  # Evita falha se o Docker ainda não estiver ativo

      # --- Instala NVM e Node.js LTS ---
      - su - victorpersike -c "export PROFILE=/home/victorpersike/.bashrc && \
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && \
          export NVM_DIR=/home/victorpersike/.nvm && \
          [ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\" && \
          nvm install --lts && \
          nvm alias default 'lts/*' && \
          echo 'export NVM_DIR=\"$HOME/.nvm\"' >> /home/victorpersike/.bashrc && \
          echo '[ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"' >> /home/victorpersike/.bashrc"

      # --- Limpeza final ---
      - apt-get clean
      - rm -rf /var/lib/apt/lists/*

  # --- ESTADO FINAL ---
  power-state:
    delay: 5
    mode: reboot
