#cloud-config
autoinstall:
  version: 1
  identity:
    realname: 'Dionatan Simioni'
    hostname: ubuntu-test-crypt
    username: diolinux
    # NOVO HASH SHA512CRYPT (fornecido por você)
    password: '$6$A9DbYaGQ3fq63Bxr$mZpgT1rHmtXEIotzNmqJdxXOMV6JKKp9bNvhyHW0AWAVWcs1Wrj1jHH5N/VtgP2UVpsUD/jzdCbyO.dhQqZUq/' 
  locale: pt_BR.utf8
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo"

  # --- CONFIGURAÇÃO DE ARMAZENAMENTO AUTOMÁTICA E ROBUSTA ---
  # Utiliza o layout automático (mais confiável) para criptografia total.
  storage:
    layout:
      name: encrypted # Usa o layout automático de criptografia total (LUKS sobre LVM)
      device: /dev/nvme0n1 # Disco a ser usado
      key: Avita123 # Senha de criptografia em texto plano
      
  # --- Configurações de Pós-Instalação ---
  updates: all
  shutdown: reboot
