#cloud-config
autoinstall:
  version: 1

  # CONFIGURAÇÃO DE ARMAZENAMENTO (Criptografia e LVM)
  storage:
    wipe: all
    layout:
      name: lvm
      match:
        path: /dev/nvme0n1
      # SENHA DE CRIPTOGRAFIA ALTERADA AQUI
      password: 'Senha2024'
  
  # CONFIGURAÇÕES DE SISTEMA
  identity:
    hostname: daniel_sammartano
    username: Daniel.Sammartano
    # SENHA DO USUÁRIO ALTERADA AQUI
    password: 'Senha2024'
    
  locale: pt_BR
  timezone: America/Sao_Paulo
  keyboard:
    layout: br

  # INSTALAÇÃO DE APLICATIVOS (APT e SNAP)
  packages:
    - docker.io
    - git
    - gimp
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - wget
    - libglib2.0-bin 

  snaps:
    - name: spotify
      channel: stable
    - name: postman
      channel: stable
    - name: slack
      channel: stable
    - name: code
      channel: stable
      classic: true
    - name: dbeaver-ce
      channel: stable
      
  # Configurações adicionais
  codecs:
    install: true
  drivers:
    install: true
  updates: all

  # COMANDOS DE PÓS-INSTALAÇÃO (ROOT)
  late-commands:
    # Atualiza pacotes e repositórios
    - curtin in-target -- apt update
    - curtin in-target -- apt upgrade -y
    # Adiciona o usuário ao grupo docker
    - curtin in-target -- usermod -aG docker Daniel.Sammartano
      
  # AÇÃO FINAL
  power-state:
    delay: 5
    mode: reboot
