#cloud-config
autoinstall:
  version: 1
  
  # ====================================================================
  # CONFIGURAÇÃO DE ARMAZENAMENTO (MAIS SIMPLES)
  # ====================================================================
  storage:
    wipe: all
    layout:
      name: lvm
      match: 
        path: /dev/nvme0n1
      password: Senhafoda123@ 

  # ====================================================================
  # CONFIGURAÇÕES DE SISTEMA
  # ====================================================================
  identity:
    hostname: notebook-ubuntu
    username: testuser
    # Usando o hash fornecido anteriormente, que é o formato mais seguro
    password: "$6$EAyehhfqepzaGX78$k4Qceki0nxJKS2.ZxcWyWjn7db3p7/0Qu.S6pr32pIqVpzfFmwnOj/.XKgY6x3ADG077lE.DoNwMpXZ2aXr3q." 
    
  # CORREÇÃO 1: 'package' não existe. Se precisar instalar pacotes
  # adicionais, use 'packages' (no plural). Se for apenas para instalar
  # o Ubuntu Server, esta seção pode ser omitida.
  # Se você quer o desktop, você instalaria o pacote 'ubuntu-desktop'.
  # Neste caso, vamos instalar o servidor padrão:
  
  # Instalação padrão (não requer a chave 'package')
  # packages:
  #   - ubuntu-server
  
  locale: pt_BR
  timezone: America/Sao_Paulo
  
  # CORREÇÃO 2: Simplificação do teclado
  keyboard:
    layout: br
    # 'variant: abnt2' removido para evitar o erro 'Unknown keyboard variant'

  # ====================================================================
  # PÓS-INSTALAÇÃO E AÇÃO FINAL
  # ====================================================================
  late-commands:
    - curtin in-target -- apt update
    - curtin in-target -- apt upgrade -y
    
  # CORREÇÃO 3: 'power-state' deve ser de nível superior
  power-state:
    delay: 5
    mode: reboot
