#cloud-config
autoinstall:
  version: 1

  # --- ARMAZENAMENTO COM LVM E CRIPTOGRAFIA ---
  storage:
    wipe: all
    layout:
      name: lvm
      match:
        path: /dev/nvme0n1
      password: "#FormatAvita@@!"

  # --- IDENTIDADE DO SISTEMA ---
  identity:
    hostname: AVTec-victorpersike
    username: victorpersike
    password: "$6$vEfMZxxLdKOo3CBb$atGwGiCpF.ZlVPS6A3vawQYlYAYgZaEhdhAYMGpw5OeZm3t2rxLqcpQCouS9jro2fwb9uQ3Wm21QTVR1JIAEU0"

  # --- LOCALIZAÇÃO ---
  locale: pt_BR
  timezone: America/Sao_Paulo

  keyboard:
    layout: br

  # --- PACOTES APT ---
  packages:
    - docker.io
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - gimp
    - git
    - wget
    - unzip
    - nano
    - software-properties-common

  # --- PACOTES SNAP ---
  snaps:
    - name: spotify
      channel: stable
      classic: false
    - name: postman
      channel: stable
      classic: false
    - name: slack
      channel: stable
      classic: false
    - name: code
      channel: stable
      classic: true
    - name: dbeaver-ce
      channel: stable
      classic: false
    - name: dotnet-sdk
      channel: 8.0/stable
      classic: true

  # --- DRIVERS E CODECS ---
  codecs:
    install: true
  drivers:
    install: true
  updates: all

  # --- CONFIGURAÇÕES PÓS-INSTALAÇÃO ---
  user-data:
    runcmd:
      # --- Teclado ---
      - setxkbmap -model thinkpad -layout br
      - su - victorpersike -c "echo 'setxkbmap -model thinkpad -layout br' >> /home/victorpersike/.xsessionrc"
      - curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash && . "$HOME/.nvm/nvm.sh" && nvm install 18 && nvm use 18
      - sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose && docker-compose --version

  # --- ESTADO FINAL ---
  power-state:
    delay: 5
    mode: reboot
