#cloud-config
autoinstall:
  version: 1
  
  # --- Configuração de Armazenamento com LVM e Criptografia ---
  storage:
    wipe: all
    layout:
      name: lvm
      match:
        path: /dev/nvme0n1 # Alvo: disco NVMe
      password: "#FormatAvita@@!" # Atenção: Senha da criptografia em texto plano no arquivo
      
  # --- Identidade do Sistema e Usuário ---
  identity:
    hostname: AVTec-victorpersike
    username: victorpersike
    # Senha do usuário criptografada (SHA-512)
    password: "$6$vEfMZxxLdKOo3CBb$atGwGiCpF.ZlVPS6A3vawQYlYAYgZaEhdhAYMGpw5OeZm3t2rxLqcpQCouS9jro2fwb9uQ3Wm21QTVR1JIAEU0"
  
  # --- Localização e Idioma ---
  locale: pt_BR
  timezone: America/Sao_Paulo
  keyboard:
    layout: br
    
  # --- Pacotes DEB (APT) ---
  packages:
    - docker.io
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - gimp
    - git
    - wget
  
  # --- Pacotes Snap ---
  snaps:
    - name: spotify
      channel: stable
      classic: false
    - name: postman
      channel: stable
      classic: false
    - name: slack
      channel: stable
      classic: false
    - name: code
      channel: stable
      classic: true # Permite acesso total ao sistema (necessário para o VS Code)
    - name: dbeaver-ce
      channel: stable
      classic: false
    # Adicionando .NET Core SDK 8.0 via Snap para simplificar
    - name: dotnet-sdk
      channel: 8.0/stable
      classic: true

  # --- Drivers e Codecs ---
  codecs:
    install: true
  drivers:
    install: true
  updates: all # Habilita updates durante a instalação inicial

  # --- Comandos Pós-Instalação (Executados no Primeiro Boot) ---
  # O bloco late-commands foi removido devido à falha de download.
  # Usaremos 'user-data/runcmd' para a atualização, que é mais estável.
  # Atenção: Este bloco 'user-data' é a solução para o erro 100.
  user-data:
    runcmd:
      # 1. Atualiza a lista de pacotes (necessário após a falha anterior)
      - apt update
      # 2. Executa o upgrade completo do sistema
      - apt upgrade -y

  # --- Estado Final ---
  power-state:
    delay: 5
    mode: reboot
