#cloud-config
autoinstall:
  version: 1
  
  # ====================================================================
  # CONFIGURAÇÃO DE ARMAZENAMENTO
  # ====================================================================
  storage:
    wipe: all
    layout:
      name: lvm
      match:  
        path: /dev/nvme0n1
      password: "$6$62BXzCtLeYnZrhUs$1n39Rl1ZHCW7G9M7CKe2d93DVG/HOffMXjoZuo7e190jVr0IoVlchVNdGL2wX2ueQHKNSno5tJJ5i9rMTqDDs1"

  # ====================================================================
  # CONFIGURAÇÕES DE SISTEMA (Identidade e Localização)
  # ====================================================================
  identity:
    hostname: daniel_sammartano
    username: testefinal
    password: "$6$62BXzCtLeYnZrhUs$1n39Rl1ZHCW7G9M7CKe2d93DVG/HOffMXjoZuo7e190jVr0IoVlchVNdGL2wX2ueQHKNSno5tJJ5i9rMTqDDs1"  
    
  locale: pt_BR
  timezone: America/Sao_Paulo
  
  keyboard:
    layout: br

  # ====================================================================
  # INSTALAÇÃO DECLARATIVA DE APLICATIVOS (APT e SNAP)
  # ====================================================================
  packages:
    # Pacotes APT essenciais (Docker, Git, utilitários, libglib2.0-bin para gsettings)
    - docker.io
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - gimp
    - git
    - wget
    - libglib2.0-bin # Necessário para o comando 'gsettings'

  snaps:
    # Aplicações instaladas via Snap Store
    - name: spotify
      channel: stable
      classic: false
    - name: postman
      channel: stable
      classic: false
    - name: slack
      channel: stable
      classic: false
    - name: code # VS Code
      channel: stable
      classic: true
    - name: dbeaver-ce
      channel: stable
      classic: false
      
  # Configurações adicionais
  codecs:
    install: true
  drivers:
    install: true
  updates: all

  # ====================================================================
  # COMANDOS DE PÓS-INSTALAÇÃO (Executados como ROOT durante a instalação)
  # ====================================================================
  late-commands:
    # 1. Update/Upgrade inicial
    - curtin in-target -- apt update
    - curtin in-target -- apt upgrade -y

    # 2. Apenas baixa o wallpaper para uma pasta pública do sistema.
    #    Não tentamos definir o gsettings aqui.
    - curtin in-target -- wget -O /usr/share/backgrounds/custom-wallpaper.png https://i.ibb.co/cwtDVCS/Frame-6.png
      
  # ====================================================================
  # CONFIGURAÇÃO DE USUÁRIO (Executado como 'testefinal' NO PRIMEIRO BOOT)
  # Esta é a forma mais simples e garantida de definir o wallpaper.
  # ====================================================================
  user-data:
    runcmd:
      # O sistema rodará estes comandos como 'testefinal' no primeiro login
      - gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/custom-wallpaper.png"
      - gsettings set org.gnome.desktop.background picture-uri-dark "file:///usr/share/backgrounds/custom-wallpaper.png"
      
  power-state:
    delay: 5
    mode: reboot
